#!/usr/bin/env node

'use strict';

var validNumbers = require('../lib/utilities/validNumbers');
var insertionSort = require('../lib/sorts/insertionSort');

// Sanitize input
if (!validNumbers()) {
	return false;
}
console.log(insertionSort(process.argv));