#!/usr/bin/env node

'use strict';

var validNumbers = require('../lib/utilities/validNumbers');
var shellSort = require('../lib/sorts/shellSort');

// Sanitize input
if (!validNumbers()) {
	return false;
}
console.log(shellSort(process.argv));